# Generated by Django 4.1.1 on 2022-10-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('place', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('start', models.IntegerField()),
                ('end', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=250)),
                ('tasks', models.JSONField()),
            ],
        ),
    ]
