# Generated by Django 4.1.1 on 2022-10-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_tec', models.ImageField(upload_to='core')),
                ('img_proj', models.ImageField(upload_to='core')),
                ('desc', models.CharField(max_length=250)),
            ],
        ),
    ]
